# Site
title:              Ehtesham Hasnain
author:             Ehtesham Hasnain
bio:                'Geoengineer and developer'
description:        "Blog posts and more"
locale:             en_DE
baseurl: "" # the subpath of your site, e.g. /blog
url: "ehasnain.github.io" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author: Ehtesham Hasnain

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   ehasnain

# Social
analytics-id:       "default"
twitter:            ehteshamtweets
facebook:           ehteshamhasnain
instagram:          ehteshamhasnain
github:             ehasnain
linkedin:           ehteshamhasnain

# personal
location:           Stuttgart, Germany
phone:              +49-176-81315327
email:              ehteshamhasnain@gmail.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
